### PR TITLE
added basic google auth

### PR DESCRIPTION
**Pull request by dhuber666**
How do you know which api keys you need exactly? In order for the server to work you need: 

* googleClientID and googleClientSecret from http://console.developers.google.com/
* mongoDB URL (grab one from mLab.com)
* cookie-session key (a random one which you can add yourself) 

I think there is a better way for the future how we handle exchanging keys. 

What do you think?

### CODE REVIEW

**Comment by dhuber666** [comment]
Another thing to mention:

You can't connect it with the frontend right now. So linking from the frontend to `/auth/google` won't work right now. I will add this later this day (I need to proxy the request to the server).

**Comment by charliearlie** [comment]
I'll be honest with you, I'm not very knowledgable on Google auth on a JS server. I remember you mentioning Firebase. How come you didn't want to use that? Just to learn websockets?

**Comment by dhuber666** [comment]
For one to have our own backend and learn stuff in the backend. And second because I find firebase auth + db very hard to use with redux. 
Have you used it before with redux? Maybe we can use it but I need a lot more knowledge of it 😄 

But yeah on the other hand you never used passport and google auth it's the same for you. 

What is your suggestion? Maybe you show me how to implement firebase in a good documented way and I will learn it that way?

**Comment by charliearlie** [comment]
I am happy to go with what we're doing for learning! But in the front end, I really don't think we need Redux. Redux is for large applications when there's a lot of state to manage. The only state we need to manager is the user and how many times they've clicked the panel.

**Comment by dhuber666** [comment]
Yeah but eventually it will become a big application :D  Joke, I get your point. 
For now redux is really not necessary. 

So we keep going with passport? I can give you an explanation what everything is doing, or I could comment it if you like? Just tell me how you like it.

**Pull request closed without merging**
